[tool]
name = "Timezone_Based_task_Execution"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
git = "https://github.com/chandanyadav6812/Timezone-based-Task-Execution"

[dependencies]
python = "^3.7"
python-dateutil = "^2.8.1"
pytz = "^2021.1"
